### ISSUE TITLE
copy / paste

### ISSUE THREAD

**Issue by Exotikcheatt** [Extravi/cs2-kernel-esp#1]
https://github.com/maxiwee69/CS2-kernel-cheat =)

**Comment by Extravi** [comment]
> https://github.com/maxiwee69/CS2-kernel-cheat =)

it's not copy paste I followed a video for the driver and he did the same thing https://youtu.be/n463QJ4cjsU

I also followed this video for the esp
https://youtu.be/wH6QsBshx8o

**Comment by Extravi** [comment]
![Screenshot_20240410-195738.png](https://github.com/Extravi/cs2-kernel-esp/assets/98912029/6815562c-c0e7-4791-9f16-caac670c7790)

you can see that he didn't author the original driver source code himself he got it from a YouTube tutorial also I didn't copy anything from that repository I followed a YouTube tutorial just like he did

**Comment by Extravi** [comment]
@Exotikcheatt Read the above contents and are you still going to accuse me of "copy and paste"

**Comment by Extravi** [comment]
also how did you even find this repository

**Comment by Extravi** [comment]
also that repo does not have esp
